// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5901.Steamworks.subsystems;

import org.usfirst.frc5901.Steamworks.RobotMap;
import org.usfirst.frc5901.Steamworks.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Intake extends Subsystem {


    public void StartCollector(){
    	RobotMap.collectorMotor.set(1.0);
    }
    public void StopCollector(){
    	RobotMap.collectorMotor.set(0.0); 
    }
    
    public void ReverseCollector(){
    	RobotMap.collectorMotor.set(-1.0);
    }
    public void initDefaultCommand() {
    	setDefaultCommand(new StopCollector());

    }
}

