// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5901.Steamworks.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc5901.Steamworks.Robot;
import org.usfirst.frc5901.Steamworks.RobotMap;

/**
 *
 */
public class AutonomousStraight extends Command {
	protected double power;
	protected double distance;
	
    public AutonomousStraight(double power, double distance) {
    	requires(Robot.drivetrain);
    	this.power = power;
    	this.distance = distance;
    }

    // Called just before this Command runs the first time
    protected void initialize() {

    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	System.out.println(RobotMap.drivetrainGodKevinGyro.getAngle());
    	if (RobotMap.leftEncoder.getDistance() < distance)
    	{
    		if (RobotMap.leftEncoder.getDistance() < distance - 30)
    		{
    			Robot.drivetrain.autoStraight(power);
    		}
    		else
    		{
    			Robot.drivetrain.autoStraight(0.1);
    		}
    	}
    	else
    	{
    		Robot.drivetrain.stopDrive();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetrain.stopDrive();	
    }
    
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
