// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5901.Steamworks.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc5901.Steamworks.Robot;

/**
 *
 */
public class AutonomousMiddleGear extends CommandGroup {

    public AutonomousMiddleGear() {
    	//Reset gyro & encoder
    	addSequential(new StopDrive(), 0.3);
  
    	
    	//113" to reach airship
    	//Drive straight, stop for 3 seconds
        addSequential(new AutonomousStraight(0.3,118-39.5), 3); 
        addSequential(new StopDrive(), 3.0);
        
        //Drive backwards and stop
        addSequential(new AutonomousBackwards(0.5,100), 0.5);
        addSequential(new StopDrive(), 0.3);
        
        //Turn 90 degrees and stop
        addSequential(new AutonomousTurn(90), 2.0);
        addSequential(new StopDrive(), 0.3);
        
        //Drive straight and stop
        addSequential(new AutonomousStraight(0.5,100), 1.0);        
        addSequential(new StopDrive(), 0.3);
        
        //Turn -90 degrees and stop
        addSequential(new AutonomousTurn(-90), 2.0);
        addSequential(new StopDrive(), 0.3);
        
        //Drive straight and stop
        addSequential(new AutonomousStraight(0.5,130), 1.0);
        addSequential(new StopDrive(), 0.3);
        
    }

    // Called just before this Command runs the first time
    protected void initialize() {

    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {

    }
    

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetrain.stopDrive();	
    }
    
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
